name: flutter_ex
description: "Learn Flutter"
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  assets: # Images
    - assets/
    - assets/card/
  uses-material-design: true